{{ if and .Values.nginx.deploy .Values.global.minikube }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-nginx
  namespace: kube-system
spec:
  type: ExternalName
  externalName: {{ include "cytomine.name" . }}-nginx.default.svc.cluster.local
{{ end }}
