apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine.name" . }}-core
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine.name" . }}-core
  policyTypes:
    - Ingress
    - Egress
  egress:
  #Mongodb
    - to:
         - podSelector:
             matchLabels:
               app: {{ include "cytomine.name" . }}-mongodb
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.mongodb.port }}
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.mongodb.statusPort }}
  #Minikube IP
    - to:
        - ipBlock:
            cidr: {{ .Values.global.publicIP }}
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: 443
        - protocol: {{ .Values.global.protocol }}
          port: 80
        - protocol: {{ .Values.global.protocol }}
          port: {{.Values.nginx.port }}
  #Postgres
    - to:
         - podSelector:
             matchLabels:
               app: {{ include "cytomine.name" . }}-postgis
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.postgresql.port }}
  #Rabbitmq
    - to:
         - podSelector:
             matchLabels:
               app: {{ include "cytomine.name" . }}-rabbitmq
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.rabbitmq.port }}
  #Bio-format
    - to:
         - podSelector:
             matchLabels:
               app: {{ include "cytomine.name" . }}-bioformat
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.bioformat.port }}
  #Ingress-nginx
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: ingress-nginx
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.nginx.port }}
        - protocol: {{ .Values.global.protocol }}
          port: 443
        - protocol: {{ .Values.global.protocol }}
          port: 80
  #Kube-system
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP

  ingress:
  #Nginx
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine.name" . }}-nginx
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.core.port }}
