apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cytomine-core
spec:
  podSelector:
    matchLabels:
      app: cytomine-core
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
         - podSelector:
             matchLabels:
               app: cytomine-mongodb
      ports:
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 28017

    - to:
        - ipBlock:
            cidr: {{ .Values.global.publicIP }}

    - to:
         - podSelector:
             matchLabels:
               app: cytomine-postgis
      ports:
        - protocol: TCP
          port: 5432

    - to:
         - podSelector:
             matchLabels:
               app: cytomine-rabbitmq
      ports:
        - protocol: TCP
          port: 27017
        - protocol: TCP
          port: 28017

    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: ingress-nginx
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80

    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cytomine-nginx
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80










    # - from:
    #     - podSelector:
    #         matchLabels:
    #           app: cytomine-rabbitmq
    #   ports:
    #     - protocol: TCP
    #       port: 5672
    #     - protocol: TCP
    #       port: 15692
    #     - protocol: TCP
    #       port: 4369


