apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cytomine-core
spec:
  podSelector:
    matchLabels:
      app: cytomine-core
  policyTypes:
    - Ingress
    - Egress
  egress:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cytomine-nginx
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80

    # - from:
    #      - podSelector:
    #          matchLabels:
    #            app: cytomine-mongodb
    #   ports:
    #     - protocol: TCP
    #       port: 27017
    #     - protocol: TCP
    #       port: 28017








    # - from:
    #     - podSelector:
    #         matchLabels:
    #           app: cytomine-rabbitmq
    #   ports:
    #     - protocol: TCP
    #       port: 5672
    #     - protocol: TCP
    #       port: 15692
    #     - protocol: TCP
    #       port: 4369


