apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cytomine-pims
spec:
  podSelector:
    matchLabels:
      app: cytomine-pims
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: pims-cache
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: ingress-nginx
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    - to:
        - ipBlock:
            cidr: 192.168.49.2/32
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    - to:
        - namespaceSelector:
            matchLabels:
               kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cytomine-nginx
      ports:
        - protocol: TCP
          port: 5000

