apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine.name" . }}-pims
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine.name" . }}-pims
  policyTypes:
    - Egress
    - Ingress
  egress:
  # Pims-cache
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine.name" . }}-pims-cache
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.pims_cache.port }}
  # RabbitMQ
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine.name" . }}-rabbitmq
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.rabbitmq.port }}
  #Ingress-nginx
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - podSelector:
            matchLabels:
              app: ingress-nginx
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.nginx.port }}
        - protocol: {{ .Values.global.protocol }}
          port: 443
        - protocol: {{ .Values.global.protocol }}
          port: 80
  #Minikube IP
    - to:
        - ipBlock:
            cidr: {{ .Values.global.publicIP }}
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: 443
        - protocol: {{ .Values.global.protocol }}
          port: 80
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.nginx.port }}
  #Kube-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
  ingress:
  #Nginx
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine.name" . }}-nginx
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.pims.port }}

