# Default values for cytomine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# Globals
#

global:
  domainName: "cytomine.local"
  use_tls: false
  affinity: {}
  tolerations: {}
readOnceStorageClass: ""
readManyStorageClass: ""

singularityStorage: "10Gi"
tempImageStorage: "1Gi"
imageStorage: "3Gi"
mongodbStorage: "1Gi"
postgresStorage: "3Gi"

# Email settings
adminEmail: info@cytomine.coop
emailSender: your.email@gmail.com
emailReceiver: receiver@XXX.com
smtpPass: null
smtpHost: smtp.gmail.com
smtpPort: 587

#
# Ingress - these are things that has to do with the user facing webpage
#
ingress:
  annotations: {}


#
# Services - these are the services deployed by this chart
#

rabbitmq:
  deploy: true
  port: 5672
  managementPort: 15692
  empdPort: 4369
  image:
    pullPolicy: Always
    repository: rabbitmq
    tag: "3.10"
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "400m"

postgresql:
  deploy: true
  port: 5432
  image:
    pullPolicy: Always
    repository: cytomine/postgis
    tag: 15-3.3-alpine-1.2.1
  user: docker
  database: docker
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

mongodb:
  deploy: true
  port: 27017
  statusPort: 28017
  image:
    pullPolicy: Always
    repository: mongo
    tag: 4.4.18-focal
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

pims_cache:
  deploy: true
  port: 6379
  image:
    pullPolicy: Always
    repository: redis
    tag: 7.0.8
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "256Mi"
      cpu: "200m"

bioformat:
  deploy: true
  port: 4321
  image:
    pullPolicy: Always
    repository: cytomine/bioformat
    tag: v1.2.0
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

core:
  deploy: true
  port: 8080
  image:
    pullPolicy: Always
    repository: cytomine/core
    tag: 4.3.6
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  # These variables default to a uuid (v4) if not set
  # adminPassword: null
  # adminPrivKey: null
  # adminPubKey: null
  # superAdminPrivKey: null
  # superAdminPubKey: null
  # imsPrivKey: null
  # imsPubKey: null
  # rabbitmqPrivKey: null
  # rabbitmqPubKey: null

pims:
  deploy: true
  port: 5000
  image:
    pullPolicy: Always
    repository: cytomine/pims
    tag: 0.13.6
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "1000m"

nginx:
  deploy: true
  port: 80
  serverID: null
  image:
    pullPolicy: Always
    repository: cytomine/nginx
    tag: 1.22.1-1.2.0
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

web_ui:
  deploy: true
  port: 80
  image:
    pullPolicy: Always
    repository: cytomine/web_ui
    tag: 2.6.1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  url_core: http://cytomine.local
  url_upload: http://upload.cytomine.local
  commercial_version: CE2023.1

#
# Kuberenetes things
#

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""

containerSecurity:
  allowPrivilegeEscalation: false  # do not allow the container to switch to a user with more permissions
  privileged: false  # the container is not privileged (usually the default)

