{{ if .Values.iip_off.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-iip-official
  labels:
    role: iip-official
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-iip-official
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-iip-official
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: iip-official
        app: {{ template "cytomine.name" . }}-iip-official
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
          runAsUser: {{ .Values.podSecurity.runAsUser }}
          runAsGroup: {{ .Values.podSecurity.runAsGroup }}
          fsGroup: {{ .Values.podSecurity.fsUserGroup }}
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: {{ template "cytomine.name" . }}-image-claim
        - name: nginx-config
          configMap:
            name: {{ include "cytomine.name" . }}-iip-official-config
      containers:
        - name: {{ .Chart.Name }}-iip-official
          image: "{{ .Values.iip_off.image.repository }}:{{ .Values.iip_off.image.tag }}"
          imagePullPolicy: {{ .Values.iip_off.image.pullPolicy }}
          volumeMounts:
            - name: images
              mountPath: "/data/images"
            - name: nginx-config
              mountPath: /config-temp/nginx.conf.sample
              subPath: nginx.conf.sample
          command: ["/bin/sh"]
          args: ["-c", "cp /config-temp/nginx.conf.sample /tmp/nginx.conf.sample && /tmp/deploy.sh"]
          securityContext:
            privileged: true
          env:
          - name: NB_IIP_PROCESS
            value: "10"
          - name: MEMCACHED_SERVERS
            value: {{ template "cytomine.name" . }}-memcached:{{ .Values.memcached.port }}
          ports:
            - name: http
              containerPort: {{ .Values.iip_off.port }}
          resources:
            {{- toYaml .Values.iip_off.resources | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
