{{ if .Values.k8s_software_router.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-k8s-software-router-secret
type: Opaque
data:
  settings.yaml: |-
    {{ (tpl (.Files.Get "configs/software_router.conf") . ) | b64enc | nindent 4 }}
{{ end }}
