{{ if .Values.software_router.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-software-router
  labels:
    role: software-router
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-software-router
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-software-router
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: software-router
        app: {{ template "cytomine.name" . }}-software-router
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      volumes:
        - name: singularity-images
          persistentVolumeClaim:
            claimName: {{ template "cytomine.name" . }}-singularity-claim
        - name: software-router-secret
          secret:
            defaultMode: 0400
            secretName: {{ include "cytomine.name" . }}-software-router-secret
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      initContainers:
        - name: core-check
          image: alpine:3.14
          command: ["wget"]
          args: ["{{ .Values.protocol }}://{{ .Values.serverName }}/api/user/current.json"]
      containers:
        - name: {{ .Chart.Name }}-software-router
          image: "{{ .Values.software_router.image.repository }}:{{ .Values.software_router.image.tag }}"
          imagePullPolicy: {{ .Values.software_router.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "cd /software_router; java -jar Cytomine-software-router.jar | tee /tmp/log.out"]
          volumeMounts:
            - mountPath: "/data/softwares/images"
              name: singularity-images
            - name: software-router-secret
              mountPath: /software_router/config.groovy
              subPath: config.groovy
            - name: software-router-secret
              mountPath: /root/.ssh/id_rsa
              subPath: id_rsa
            - name: dockersock
              mountPath: /var/run/docker.sock
          resources:
            {{- toYaml .Values.software_router.resources | nindent 12 }}
{{ end }}
