apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine.name" . }}-bioformat
spec:
  podSelector:
    matchLabels:
      service: {{ include "cytomine.name" . }}-bioformat
  policyTypes:
    - Egress
    - Ingress
  ingress:
  egress: