apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine.name" . }}-bioformat
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine.name" . }}-bioformat
  policyTypes:
    - Egress
    - Ingress
  ingress:
  #Core
  - from:
      - podSelector:
          matchLabels:
            app: {{ include "cytomine.name" . }}-core
    ports:
      - protocol: {{ .Values.global.protocol }}
        port: {{ .Values.bioformat.port }}
  egress: