apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cytomine.name" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
spec:
  rules:
    - host: {{ .Values.global.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-nginx
                port:
                  number: {{ .Values.nginx.port }}
    - host: {{ .Values.global.urlUpload }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-nginx
                port:
                  number: {{ .Values.nginx.port }}
    - host: {{ .Values.global.imsDomainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cytomine.name" . }}-nginx
                port:
                  number: {{ .Values.nginx.port }}
  {{ if .Values.global.use_tls }}
  tls:
  - hosts:
    - {{ .Values.global.domainName }}
    secretName: {{ include "cytomine.name" . }}-ingress-tls
  {{ end }}
