{{ if .Values.rabbitmq.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-rabbitmq-secret
type: Opaque
data:
  init.sh: |-
    {{ (tpl (.Files.Get "configs/rabbitmq_init.sh") . ) | b64enc | nindent 4 }}
{{ end }}
