{{ if .Values.rabbitmq.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-rabbitmq
spec:
  selector:
    app: {{ include "cytomine.name" . }}-rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
      protocol: TCP
{{ end }}
