{{ if .Values.web_ui.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-web-ui
  annotations:
    kube-score/ignore: pod-probes,container-security-context-user-group-id
  labels:
    role: web-ui
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-web-ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-web-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: web-ui
        app: {{ template "cytomine.name" . }}-web-ui
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 20000
        fsGroup: 20000
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "cytomine.name" . }}-web-ui-config
        configMap:
          name: {{ include "cytomine.name" . }}-web-ui-config
      - name: {{ include "cytomine.name" . }}-web-ui-localtime
        configMap:
          name: {{ include "cytomine.name" . }}-localtime
      - name: temp
        emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}-web-ui
          image: "{{ .Values.images.web_ui }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
          - name: URL_CORE
            value: {{ .Values.web_ui.url_core }}
          - name: URL_UPLOAD
            value: {{ .Values.web_ui.url_upload }}
          - name: CYTOMINE_COMMERCIAL_VERSION
            value: {{ .Values.web_ui.commercial_version }}
          volumeMounts:
            - name: {{ include "cytomine.name" . }}-web-ui-localtime
              mountPath: /etc/localtime
              subPath: Europe
            - name: {{ include "cytomine.name" . }}-web-ui-config
              mountPath: /cm_configs/app/configuration.json.sample
              subPath: configuration.json.sample
            - name: {{ include "cytomine.name" . }}-web-ui-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: temp
              mountPath: /tmp
            - name: temp
              mountPath: /app
            - name: temp
              mountPath: "/var/cache/nginx/client_temp"
            - name: temp
              mountPath: "/var/cache/nginx/proxy_temp"
            - name: temp
              mountPath: "/var/cache/nginx/fastcgi_temp"
            - name: temp
              mountPath: "/var/cache/nginx/uwsgi_temp"
            - name: temp
              mountPath: "/var/cache/nginx/scgi_temp"
            - name: temp
              mountPath: "/var/run"
            - name: temp
              mountPath: /etc/nginx/proxy_temp
          ports:
            - name: http
              containerPort: {{ .Values.web_ui.port }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurity.allowPrivilegeEscalation }}
            privileged: {{ .Values.containerSecurity.privileged }}
            readOnlyRootFilesystem: {{ .Values.containerSecurity.readOnlyRootFilesystem }}
          resources:
            {{- toYaml .Values.web_ui.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-web-ui-init
          image: "{{ .Values.images.web_ui }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.containerSecurity.readOnlyRootFilesystem }}
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              cp -r /app/* /fix/;
          volumeMounts:
            - name: temp
              mountPath: /fix
          resources:
            {{- toYaml .Values.web_ui.resources | nindent 12 }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
