{{ if .Values.core.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-core
spec:
  selector:
    app: {{ include "cytomine.name" . }}-core
  ports:
    - name: http
      port: {{ .Values.core.port }}
      targetPort: {{ .Values.core.port }}
      protocol: TCP
{{ end }}
