apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cytomine.name" . }}-pims-cache
spec:
  podSelector:
    matchLabels:
      app: {{ include "cytomine.name" . }}-pims-cache
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "cytomine.name" . }}-pims
      ports:
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.pims_cache.port}}
        - protocol: {{ .Values.global.protocol }}
          port: {{ .Values.pims.port }}
  egress:
