{{ if .Values.postgresql.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-postgresql-secret
type: Opaque
data:
  password: NHVrMjMydmJjZVFhWTBGM3R4bThLcEsraWZyc3N3M1Jxby9NR2VTd1RlZz0=
{{ end }}