{{ if .Values.postgresql.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-postgis
spec:
  selector:
    app: {{ include "cytomine.name" . }}-postgis
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
{{ end }}
