version: 1

formatters:
  basic:
    class: pims.logger.StdoutFormatter
    format: "[%(process)s][%(threadName)s] %(message)s"
  complete:
    class: pims.logger.StdoutFormatter
    format: "[%(asctime)s][%(levelname)s][%(process)s][%(threadName)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: complete

loggers:
  pims:
    handlers: [console]
    level: DEBUG
  pims.app:
    handlers: [console]
    level: DEBUG
  pims.cytomine:
    level: DEBUG
    handlers: [console]
    propagate: false
  pyvips:
    level: INFO
  pyvips.vobject:
    level: ERROR
  uvicorn:
    level: DEBUG
  uvicorn.access:
    level: CRITICAL
#  gunicorn.error:
#    propagate: true
  cytomine.client:
    handlers: [console]
    level: DEBUG

root:
  handlers: [console]
  level: DEBUG
