{{ if .Values.mongodb.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-mongodb-secret
type: Opaque
stringData:
  password: {{ .Values.mongodb.password }}
{{ end }}