{{ if .Values.pims.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cytomine.name" . }}-pims-config
data:
    DEFAULT_ANNOTATION_ORIGIN: LEFT_TOP
    DEFAULT_IMAGE_SIZE_SAFETY_MODE: SAFE_REJECT
    LOG_CONFIG_FILE: "/app/logging.yml"
    MAX_REQUESTS: "0"
    OUTPUT_SIZE_LIMIT: "10000"
    WEB_CONCURRENCY: "16"
    cache_enabled: "true"
    task_queue_enabled: "false"
    PENDING_PATH: "/tmp/uploaded"
    PIMS_URL: http://ims.cytomine.local
    ROOT: /data/images
    CYTOMINE_PUBLIC_KEY: ff8c20fc-ccba-4495-a452-c39f87a5aa93
    CYTOMINE_PRIVATE_KEY: bdd4ae1e-1802-48a7-b251-565de0dab751
{{ end }}
---
{{ if .Values.pims.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cytomine.name" . }}-pims-logging
data:
  logging.yml:  |-
    version: 1

    formatters:
      basic:
        class: pims.logger.StdoutFormatter
        format: "[%(process)s][%(threadName)s] %(message)s"
      complete:
        class: pims.logger.StdoutFormatter
        format: "[%(asctime)s][%(levelname)s][%(process)s][%(threadName)s] %(message)s"

    handlers:
      console:
        class: logging.StreamHandler
        level: INFO
        formatter: complete

    loggers:
      pims:
        level: DEBUG
      pims.app:
        level: DEBUG
      pims.cytomine:
        level: CRITICAL
        handlers: [console]
        propagate: false
      pyvips:
        level: INFO
      pyvips.vobject:
        level: ERROR
      uvicorn:
        level: DEBUG
      uvicorn.access:
        level: CRITICAL
    #  gunicorn.error:
    #    propagate: true
      cytomine.client:
        level: INFO

    root:
      handlers: [console]
      level: DEBUG

{{ end }}