{{ if .Values.pims_cache.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-pims-cache
spec:
  selector:
    app: {{ include "cytomine.name" . }}-pims-cache
  ports:
    - name: pims-cache
      port: {{ .Values.pims_cache.port }}
      targetPort: {{ .Values.pims_cache.port }}
      protocol: TCP
{{ end }}
