# Default values for cytomine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#
# Globals
#

global:
  domainName: "cytomine.local"
  imsDomainName: "ims.cytomine.local"
  urlUpload: "upload.cytomine.local"
  use_tls: false
  affinity: {}
  tolerations: {}
  publicIP: "192.168.49.2/32"
  protocol: TCP
readOnceStorageClass: ""
readManyStorageClass: ""


# Resource settings
singularityStorage: "10Gi"
tempImageStorage: "1Gi"
imageStorage: "3Gi"
mongodbStorage: "1Gi"
postgresStorage: "3Gi"

# Email settings
adminEmail: info@cytomine.coop
emailSender: your.email@gmail.com
emailReceiver: receiver@XXX.com
smtpPass: null
smtpHost: mail.smtp
smtpPort: 587

#
# Ingress - these are things that has to do with the user facing webpage
#
ingress:
  annotations: {}

#
# Images
#
images:
  rabbitmq: rabbitmq:3.10
  postgresql: cytomine/postgis:1.3.0
  mongodb: mongo:4.4.18-focal
  pims_cache: redis:7.0.8
  bioformat: cytomine/bioformat:v1.2.0
  core: cytomine/core:4.4.0
  pims: cytomine/pims-ce-package:0.2.0
  nginx: cytomine/nginx:1.22.1-1.2.0
  web_ui: cytomine/web_ui:2.6.2
  pullPolicy: Always
#
# Services - these are the services deployed by this chart
#

# RabbitMQ - Required to use algorithms
rabbitmq:
  deploy: true
  port: 5672
  managementPort: 15692
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
      ephemeral-storage: 32Mi
    limits:
      memory: "512Mi"
      cpu: "400m"
      ephemeral-storage: 32Mi

# Postgresql - Main database.Stores most of data
postgresql:
  deploy: true
  port: 5432
  user: docker
  database: docker
  password: ZUxoMzJycTY5ckdxb0VUdElXMXl1U2wzZ0ExOHVSMzlpMGhNWjRDOHpvRT0K
  resources:
    requests:
      memory: "512Mi"
      cpu: "50m"
      ephemeral-storage: 1Gi
    limits:
      memory: "512Mi"
      cpu: "200m"
      ephemeral-storage: 1Gi

# MongoDB - Secondary database.Stores activity data
mongodb:
  deploy: true
  port: 27017
  statusPort: 28017
  username: mongoadmin
  password: password123
  database: cytomine
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
      ephemeral-storage: 1Gi
    limits:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: 1Gi

# Redis - Cache for fast image extractor
pims_cache:
  deploy: true
  port: 6379
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: 32Mi
    limits:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: 32Mi

# Bioformat - Support for additonal image formats
bioformat:
  deploy: true
  port: 4321
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: 1Gi
    limits:
      memory: "128Mi"
      cpu: "200m"
      ephemeral-storage: 1Gi

# Core - Main Cytomine Server
core:
  deploy: true
  port: 8080
  admin_password: OA9M4A382GFDNAKLmu5a/I1L0yQsXe/pmmxMelm2jwQ=
  admin_private_key: ba04b7c3-2188-45c4-ac2e-8a0bfd98afee
  admin_public_key: 1bc0d049-fbfe-4c7d-a320-4e034a5feb90
  jwt_secret: OLSE'XpvGZckJEH;nYh4Gg9rv_HY'9RAKvy7aPzxFoVNCem8QZQsGyKdqZTrYq9U1wO+bEc;F8nnRE3J4tDUK85ts^1Uc8BOzY8Q2K.v_W'RL;8fedA;VVDIZri0OjKu__tcjdM+Pa3+^^C6hcNrtRF5N^gW~w0WoWn;iNfzyGuhwu4ETMOEjpCXVMStofMQyBQrXSd1LgDtL_RC3bFK3+dJ9x_ie8J5r5oVaEpo2TOer27l85'+FCp056Ah3NNn
  rabbitmq_private_key: 706c2ccc-6b4b-4219-8604-49873bc6c288
  rabbitmq_public_key: 115068d6-fcc1-4f01-a6bb-7d5194de646e
  super_admin_private_key: 1d27e61f-a86c-4239-ad28-9398c79e1225
  super_admin_public_key: 653e466e-435f-4ff5-a501-90adeeff8c5c
  image_server_private_key: db087410-c2bd-4fa9-8aca-a9ad98226657
  image_server_public_key: ca9020d0-76fe-4f05-8371-6cbe885c2b29
  javamelody_password: iAWYk+Nc48XZToZ/z91R1hzhtoTgqJgxnq8mDa+I6Uo=
  smtp_password: password
  server_id: 69308206-ed7c-454b-90b3-5639377ccd2f
  postgis_password: ZUxoMzJycTY5ckdxb0VUdElXMXl1U2wzZ0ExOHVSMzlpMGhNWjRDOHpvRT0K
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
      ephemeral-storage: 1Gi
    limits:
      memory: "2Gi"
      cpu: "500m"
      ephemeral-storage: 1Gi

# Pims - Main Image Server
pims:
  deploy: true
  port: 5000
  public_key: ca9020d0-76fe-4f05-8371-6cbe885c2b29
  private_key: db087410-c2bd-4fa9-8aca-a9ad98226657
  pims_url: http://ims.cytomine.local
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
      ephemeral-storage: 1Gi
    limits:
      memory: "4Gi"
      cpu: "1000m"
      ephemeral-storage: 1Gi
# Nginx - Main HTTP proxy dispatching incoming requests
nginx:
  deploy: true
  port: 9000
  serverID: null
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
      ephemeral-storage: 32Mi
    limits:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: 32Mi

# Web-ui - Cytomine GUI interface
web_ui:
  deploy: true
  port: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
      ephemeral-storage: 32Mi
    limits:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: 32Mi
  url_core: http://cytomine.local
  url_upload: http://upload.cytomine.local
  commercial_version: CE2023.1

#
# Kuberenetes things
#

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname
  # template
  name: ""

containerSecurity:
  allowPrivilegeEscalation: false  # do not allow the container to switch to a user with more permissions
  privileged: false  # the container is not privileged (usually the default)
  readOnlyRootFilesystem: true  # the container does not write to the root filesystem
  userID: 20000
  groupID: 20000
  fsgroupID: 20000

