{{ if .Values.nginx.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-nginx
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: {{ include "cytomine.name" . }}-nginx
{{ end }}
