{{ if .Values.nginx.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-nginx
  labels:
    role: nginx
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-nginx
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-nginx
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: nginx
        app: {{ template "cytomine.name" . }}-nginx
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "cytomine.name" . }}-nginx-config
        configMap:
          name: {{ include "cytomine.name" . }}-nginx-config
      - name: image-temp
        persistentVolumeClaim:
          claimName: {{ template "cytomine.name" . }}-temp-image-claim
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          command: ["/usr/local/nginx/sbin/nginx"]
          volumeMounts:
            - name: {{ include "cytomine.name" . }}-nginx-config
              mountPath: /usr/local/nginx/conf/nginx.conf
              subPath: nginx.conf
            - name: image-temp
              mountPath: "/tmp/uploaded"
          ports:
            - name: http
              containerPort: {{ .Values.nginx.port }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
{{ end }}
