{{ if .Values.rabbitmq.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-rabbitmq
  labels:
    role: rabbitmq
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: rabbitmq
        app: {{ template "cytomine.name" . }}-rabbitmq
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
          runAsUser: {{ .Values.podSecurity.runAsUser }}
          runAsGroup: {{ .Values.podSecurity.runAsGroup }}
          fsGroup: {{ .Values.podSecurity.fsUserGroup }}
      volumes:
        - name: rabbitmq-secret
          secret:
            defaultMode: 0755
            secretName: {{ include "cytomine.name" . }}-rabbitmq-secret
        - name: rabbitmq-log
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          env:
          - name: RABBITMQ_PID_FILE
            value: "/var/lib/rabbitmq/mnesia/rabbit@c12b9c650697.pid"
          volumeMounts:
            - name: rabbitmq-secret
              mountPath: /init.sh
              subPath: init.sh
            - name: rabbitmq-log
              mountPath: "/var/log/rabbitmq"
          command: ["/bin/bash"]
          args: ["-c", "/init.sh"]
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.rabbitmq.managementPort }}
          securityContext:
            runAsUser: 102
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            timeoutSeconds: 15
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
