{{ if .Values.rabbitmq.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-rabbitmq
  labels:
    role: rabbitmq
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: rabbitmq
        app: {{ template "cytomine.name" . }}-rabbitmq
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          image: "{{ .Values.images.rabbitmq }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.rabbitmq.managementPort }}
            - name: empd
              containerPort: {{ .Values.rabbitmq.empdPort }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurity.allowPrivilegeEscalation }}
            privileged: {{ .Values.containerSecurity.privileged }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            timeoutSeconds: 15
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
