{{ if .Values.mongodb.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cytomine.name" . }}-mongodb-claim
spec:
  storageClassName: {{ .Values.readOnceStorageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodbStorage }}
{{ end }}
