{{ if or .Values.nginx.deploy .Values.ims.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cytomine.name" . }}-temp-image-claim
spec:
  storageClassName: {{ .Values.readManyStorageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.tempImageStorage }}
{{ end }}
