{{ if .Values.pims.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cytomine.name" . }}-pims-config
data:
  pims.conf: |-
    {{ .Files.Get "configs/pims.conf" | nindent 4 }}
{{ end }}
---
{{ if .Values.pims.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cytomine.name" . }}-pims-logging
data:
  logging.yml:  |-
    {{ .Files.Get "configs/logging.yml" | nindent 4 }}
{{ end }}