{{ if .Values.pims.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-pims-secret
type: Opaque
data:
    private_key: YmRkNGFlMWUtMTgwMi00OGE3LWIyNTEtNTY1ZGUwZGFiNzUx
    public_key: ZmY4YzIwZmMtY2NiYS00NDk1LWE0NTItYzM5Zjg3YTVhYTkz
{{ end }}