{{ if .Values.postgresql.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-postgresql-secret
type: Opaque
stringData:
  password: {{ .Values.postgresql.password }}
{{ end }}