apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cytomine-postgis
spec:
  podSelector:
    matchLabels:
      app: cytomine-postgis
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cytomine-core
      ports:
        - protocol: TCP
          port: 5432
  egress:

