{{ if .Values.postgresql.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-postgresql-secret
type: Opaque
stringData:
  password: {{ .Values.postgresql.password }}
  pg_dockeruser.sql: |-
    {{ (tpl (.Files.Get "configs/pg_dockeruser.sql") . ) | nindent 4 }}
{{ end }}