apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  private_key: N2YyZWI4ZTItNzAwMi00YzU1LWEwNWYtYjc3M2FkY2MzNWU3Cg==
  public_key: YWUxYTU1ODEtZDJjNS00N2Q1LWFlYmMtOGI3YWQ4N2FkZWYwCg==