{{ if .Values.mongodb.deploy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cytomine.name" . }}-mongodb
  labels:
    role: mongodb
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-mongodb
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: {{ include "cytomine.name" . }}-mongodb
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: mongodb
        app: {{ template "cytomine.name" . }}-mongodb
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-mongodb
          image: "{{ .Values.images.mongodb }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          volumeMounts:
            - name: mongodb-storage
              mountPath: "/data/db"
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cytomine.name" . }}-mongodb-secret
                  key: password
            - name: MONGO_INIT_DATABASE
              value: cytomine
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        storageClassName: {{ .Values.readOnceStorageClass }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodbStorage }}
{{ end }}
