{{ if .Values.mongodb.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-mongodb
spec:
  selector:
    app: {{ include "cytomine.name" . }}-mongodb
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
      targetPort: 27017
    - name: management
      port: {{ .Values.mongodb.statusPort }}
      targetPort: 28017
{{ end }}
