{{ if .Values.mongodb.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cytomine.name" . }}-mongodb-secret
type: Opaque
data:
  username: bW9uZ29hZG1pbgo=
  password: cGFzc3dvcmQxMjMK
{{ end }}