# Source: cytomine/templates/storage/temp-image-storage-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cytomine-temp-image-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
