{{ if .Values.web_ui.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-web-ui
  labels:
    role: web-ui
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-web-ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-web-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: web-ui
        app: {{ template "cytomine.name" . }}-web-ui
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      volumes:
      - name: {{ include "cytomine.name" . }}-web-ui-config
        configMap:
          name: {{ include "cytomine.name" . }}-web-ui-config
      containers:
        - name: {{ .Chart.Name }}-web-ui
          image: "{{ .Values.web_ui.image.repository }}:{{ .Values.web_ui.image.tag }}"
          imagePullPolicy: {{ .Values.web_ui.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "cytomine.name" . }}-web-ui-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: {{ include "cytomine.name" . }}-web-ui-config
              mountPath: /app/configuration.json
              subPath: configuration.json
          ports:
            - name: http
              containerPort: {{ .Values.web_ui.port }}
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.web_ui.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{ end }}
