{{ if .Values.web_ui.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-web-ui
  labels:
    role: web-ui
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-web-ui
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-web-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: web-ui
        app: {{ template "cytomine.name" . }}-web-ui
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "cytomine.name" . }}-web-ui-config
        configMap:
          name: {{ include "cytomine.name" . }}-web-ui-config
      - name: {{ include "cytomine.name" . }}-web-ui-localtime
        hostPath:
          path: /etc/localtime
      containers:
        - name: {{ .Chart.Name }}-web-ui
          image: "{{ .Values.web_ui.image.repository }}:{{ .Values.web_ui.image.tag }}"
          imagePullPolicy: {{ .Values.web_ui.image.pullPolicy }}
          env:
          - name: URL_CORE
            value: {{ .Values.web_ui.url_core }}
          - name: URL_UPLOAD
            value: {{ .Values.web_ui.url_upload }}
          volumeMounts:
            - name: {{ include "cytomine.name" . }}-web-ui-localtime
              mountPath: /etc/localtime
            - name: {{ include "cytomine.name" . }}-web-ui-config
              mountPath: /cmconfigs/app/configuration.json
              subPath: configuration.json
          ports:
            - name: http
              containerPort: {{ .Values.web_ui.port }}
          resources:
            {{- toYaml .Values.web_ui.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurity.allowPrivilegeEscalation }}
            privileged: {{ .Values.containerSecurity.privileged }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
