{{ if .Values.nginx.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cytomine.name" . }}-nginx
spec:
  selector:
    app: {{ include "cytomine.name" . }}-nginx
  ports:
    - name: http
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      protocol: TCP
{{ end }}
