{{ if or .Values.core.deploy }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cytomine.name" . }}-singularity-claim
spec:
  storageClassName: {{ .Values.readManyStorageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.singularityStorage }}
{{ end }}