{{ if .Values.bioformat.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cytomine.name" . }}-bioformat
  labels:
    role: bioformat
    app: {{ include "cytomine.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-bioformat
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cytomine.name" . }}-bioformat
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        role: bioformat
        app: {{ template "cytomine.name" . }}-bioformat
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cytomine.serviceAccountName" . }}
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: {{ template "cytomine.name" . }}-image-claim
      containers:
        - name: {{ .Chart.Name }}-bioformat
          image: "{{ .Values.bioformat.image.repository }}:{{ .Values.bioformat.image.tag }}"
          imagePullPolicy: {{ .Values.bioformat.image.pullPolicy }}
          volumeMounts:
            - name: images
              mountPath: "/data/images"
          env:
          - name: BIOFORMAT_PORT
            value: "{{ .Values.bioformat.port }}"
          resources:
            {{- toYaml .Values.bioformat.resources | nindent 12 }}
{{ end }}
